Add all required elements for case studys landing page + image with q…
concrete5/marketing.concretecms.com pull request #7
Opened 2021-04-29 18:57 UTC by bitterdev

…uote block type

2021-05-01 00:06 UTC, aembler requested changes

2021-05-01 00:06 UTC, aembler commented on public/packages/concrete_cms_marketing/blocks/page_list/templates/case_study_list/view.php
> +        <?php foreach ($pages as $page) { ?>
This is actually gonna be a summary template so we can use the same markup easily in multiple places. See the video attached to the ticket.

2021-05-01 00:06 UTC, aembler commented on public/packages/concrete_cms_marketing/src/PortlandLabs/ConcreteCmsMarketing/Provider/ServiceProvider.php
> +        $this->app['manager/view/pagination'] = $this->app->share(function ($app) {
I'm not sure we need this here? Don't we have custom paging within the Concrete CMS theme? We don't want different pagination in the theme vs in the marketing site. All the pagination should be defined within the concrete cms theme package.

2021-05-01 00:06 UTC, aembler commented on public/packages/concrete_cms_marketing/src/PortlandLabs/ConcreteCmsMarketing/Search/Pagination/View/SimplePaginationTemplate.php
> +class SimplePaginationTemplate extends Template
I think we want to move all this into the theme class.

2021-05-02 09:46 UTC, bitterdev commented on public/packages/concrete_cms_marketing/blocks/page_list/templates/case_study_list/view.php
> +        <?php foreach ($pages as $page) { ?>
@aembler Hi Andrew. I have seen the video and already replied on jira. The problem is that the summary feature doesn't work well with 3rd party packages. Please check my comments on jira. You can work anyway with that custom template. We can replace it later and switch to summary templates without touching the content.

2021-05-02 09:47 UTC, bitterdev commented on public/packages/concrete_cms_marketing/src/PortlandLabs/ConcreteCmsMarketing/Provider/ServiceProvider.php
> +        $this->app['manager/view/pagination'] = $this->app->share(function ($app) {
In Gary layouts is another pagination used for it. Therefore i have created a custom one. I will move it to the theme repository tomorrow.

2021-05-02 09:47 UTC, bitterdev commented on public/packages/concrete_cms_marketing/src/PortlandLabs/ConcreteCmsMarketing/Search/Pagination/View/SimplePaginationTemplate.php
> +class SimplePaginationTemplate extends Template
Yes will do so tomorrow :)

2021-05-03 12:32 UTC, bitterdev commented on public/packages/concrete_cms_marketing/blocks/page_list/templates/case_study_list/view.php
> +        <?php foreach ($pages as $page) { ?>
@aembler Okay i have fixed it. The updated PR takes use of summary templates. Pagination are now move to the theme package.

2021-05-04 22:35 UTC, aembler commented
I think we no longer need this pull request. If I'm wrong please reopen.

2021-05-04 22:35 UTC, closed without merging